# Generated by Django 5.1.5 on 2025-02-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='formateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='filiere',
            field=models.ManyToManyField(related_name='formateur', to='utilisateur.filiere'),
        ),
    ]
