# Generated by Django 5.1.5 on 2025-02-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_matiere_filiere_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='nom_matiere',
            field=models.CharField(max_length=150),
        ),
    ]
