# Generated by Django 5.1.5 on 2025-02-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_alter_matiere_nom_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='matiere',
        ),
    ]
