# Generated by Django 5.1.5 on 2025-02-01 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_remove_filiere_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.matiere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom_matiere',
            field=models.CharField(max_length=200),
        ),
    ]
