# Generated by Django 5.1.5 on 2025-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0010_apprenant_nom_apprenant_prenom_formateur_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='matiere',
        ),
        migrations.AddField(
            model_name='filiere',
            name='matiere',
            field=models.ManyToManyField(related_name='matiere', to='utilisateur.matiere'),
        ),
    ]
