# Generated by Django 5.1.5 on 2025-02-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0011_remove_filiere_matiere_filiere_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
