# Generated by Django 5.1.5 on 2025-02-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0012_formateur_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenant',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
