# Generated by Django 5.1.5 on 2025-02-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0013_apprenant_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=100)),
                ('heure_cours', models.TimeField()),
                ('duree', models.CharField(max_length=20)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.classe')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.formateur')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.matiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.salle')),
            ],
        ),
    ]
