# Generated by Django 5.1.5 on 2025-02-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0014_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salle',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
