# Generated by Django 5.1.5 on 2025-02-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0001_initial'),
        ('utilisateur', '0015_matiere_archive_salle_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannings.salle'),
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
    ]
