# Generated by Django 5.1.5 on 2025-02-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0002_classe_planning'),
        ('utilisateur', '0016_alter_planning_salle_delete_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='classe',
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='classe_apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannings.classe'),
        ),
        migrations.RemoveField(
            model_name='planning',
            name='formateur',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='salle',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Planning',
        ),
    ]
